import { useEffect, useRef } from 'react';

/**
 * Plays one audio clip per call turn and treats each clip's end as the cue to
 * advance — so the scripted replay's coverage board stays locked to the spoken
 * audio (the audio is the clock, not a fixed timer).
 *
 *   src      the current turn's clip URL, or null when nothing should play
 *   playing  transport state — pause/resume keeps the clip's position
 *   onEnded  fires when the current clip finishes (reveal the turn + tick coverage)
 *
 * Clips are generated by `agent-py/demo/gen_demo_audio.py` into
 * `frontend/public/demo/audio/`. Audio playback requires a prior user gesture
 * (the Start button) to satisfy browser autoplay policy.
 */
export function useCallAudio({
  src,
  playing,
  onEnded,
}: {
  src: string | null;
  playing: boolean;
  onEnded: () => void;
}) {
  const audioRef = useRef<HTMLAudioElement | null>(null);
  const endedRef = useRef(onEnded);
  endedRef.current = onEnded;

  if (audioRef.current === null && typeof Audio !== 'undefined') {
    audioRef.current = new Audio();
  }

  // Bind the ended handler once; read the latest callback via the ref.
  useEffect(() => {
    const el = audioRef.current;
    if (!el) return;
    const handler = () => endedRef.current();
    el.addEventListener('ended', handler);
    return () => el.removeEventListener('ended', handler);
  }, []);

  // Point the element at the current clip. Only reset when the source actually
  // changes, so pausing and resuming keeps the clip's playback position.
  useEffect(() => {
    const el = audioRef.current;
    if (!el) return;
    const url = src ?? '';
    if (el.getAttribute('src') !== url) {
      el.setAttribute('src', url);
      el.load();
    }
  }, [src]);

  // Play / pause to match transport state.
  useEffect(() => {
    const el = audioRef.current;
    if (!el) return;
    if (playing && src) {
      el.play().catch(() => {
        /* autoplay gate or rapid src change interrupted play — safe to ignore */
      });
    } else {
      el.pause();
    }
  }, [playing, src]);
}
